"""make user fields nullable

Revision ID: 03fc282886b8
Revises: 8953e9e81fd9
Create Date: 2026-03-06 15:20:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03fc282886b8"
down_revision: Union[str, Sequence[str], None] = "8953e9e81fd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "house_number", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "street", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "city", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "state", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "postal_code", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "country", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "country", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "postal_code", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "state", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "city", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "street", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "house_number", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
